package icebox

import (
	"bytes"
	"reflect"
	"strings"
	"unicode"
)

const (
	// Separator to use in autogenerated table names.
	tableNameSeparator string = "_"
)

type TableEntity interface {
	TableName() string
}

func getTableName(object interface{}) string {
	var name string
	if val, ok := object.(TableEntity); ok {
		name = val.TableName()
	} else {
		name = tableNameFromType(objectType)
	}
	return name
}

func tableNameFromType(object interface{}) string {
	return tableNameFromType(reflect.TypeOf(object))
}

// Extract a SQL style table name from the type of an object.
func tableNameFromType(objectType reflect.Type) string {
	var typeName = objectType.String()
	var words = splitOnCaps(typeName)

	// Build a string efficiently from the above slice of words using a buffer.
	var buffer bytes.Buffer
	i := 0
	for ; i < len(words)-1; i++ {
		buffer.WriteString(strings.ToLower(words[i]))
		buffer.WriteString(tableNameSeparator)
	}
	buffer.WriteString(words[i])
	return buffer.String()
}

// Split the given word into a slice of string all starting with
// capital letters.
func splitOnCaps(word string) []string {
	var words []string
	l := 0
	for s := word; s != ""; s = s[l:] {
		l = strings.IndexFunc(s[1:], unicode.IsUpper) + 1
		if l <= 0 {
			l = len(s)
		}
		words = append(words, s[:l])
	}
	return words
}
